[components.dev."compiler/amd-llvm/stage"]
exclude = [
  "lib/llvm/lib/clang/**",
]
[components.doc."compiler/amd-llvm/stage"]
[components.lib."compiler/amd-llvm/stage"]
include = [
  "lib/llvm/amdgcn/**",
  "lib/llvm/lib/clang/**",
]

[components.run."compiler/amd-llvm/stage"]
include = [
  "lib/llvm/bin/**",
  "lib/llvm/libexec/**",
  "lib/llvm/hip/**",
]
