# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# therock_topology_validation.cmake
# Validates that CMake subproject dependencies (BUILD_DEPS / RUNTIME_DEPS)
# are consistent with artifact_deps declared in BUILD_TOPOLOGY.toml.
#
# This catches the case where someone adds a BUILD_DEP or RUNTIME_DEPS in a
# CMakeLists.txt without updating BUILD_TOPOLOGY.toml. Without the topology
# update, enabling a single feature (e.g. -DTHEROCK_ENABLE_PRIM=ON) won't
# implicitly enable the feature's transitive dependencies, causing configure
# failures in downstream consumers.
#
# False-positive filtering:
#   Some subprojects (e.g. rocm-cmake) are declared unconditionally — outside
#   any if(THEROCK_ENABLE_*) guard — so they are always available even when
#   their artifact's feature is OFF. The validator detects this by checking
#   whether a dep's artifact feature is currently disabled yet the dep target
#   still exists.
#
#   This detection only works when THEROCK_ENABLE_ALL is OFF (so that some
#   features are actually disabled). With THEROCK_ENABLE_ALL=ON (the default),
#   all features are ON and we cannot distinguish gated from ungated
#   subprojects. In that case validation is skipped unless explicitly requested
#   via -DTHEROCK_VALIDATE_TOPOLOGY=ON.

# therock_validate_topology_deps
# Call this after all add_subdirectory() calls so that all subproject targets
# and artifact mappings are available.
function(therock_validate_topology_deps)
  if(NOT DEFINED THEROCK_TOPOLOGY_ARTIFACTS)
    return()
  endif()

  # With THEROCK_ENABLE_ALL=ON all features are enabled, making it impossible
  # to distinguish subprojects gated by if(THEROCK_ENABLE_*) from those
  # declared unconditionally. Skip unless the user explicitly opted in.
  if(THEROCK_ENABLE_ALL AND NOT THEROCK_VALIDATE_TOPOLOGY)
    return()
  endif()

  set(_errors)

  foreach(_artifact ${THEROCK_TOPOLOGY_ARTIFACTS})
    # Get this artifact's subprojects (recorded by therock_provide_artifact).
    get_property(_subprojects GLOBAL PROPERTY
      THEROCK_ARTIFACT_SUBPROJECTS_${_artifact})
    if(NOT _subprojects)
      continue()
    endif()

    # Get this artifact's transitive topology deps (generated by topology_to_cmake.py).
    set(_topology_deps "${THEROCK_ARTIFACT_DEPS_${_artifact}}")

    foreach(_subproject ${_subprojects})
      if(NOT TARGET "${_subproject}")
        continue()
      endif()

      # Collect BUILD_DEPS and RUNTIME_DEPS from the subproject target.
      get_target_property(_build_deps "${_subproject}" THEROCK_BUILD_DEPS)
      get_target_property(_runtime_deps "${_subproject}" THEROCK_RUNTIME_DEPS)
      # CMake returns "<name>-NOTFOUND" for unset properties.
      if("${_build_deps}" STREQUAL "_build_deps-NOTFOUND")
        set(_build_deps)
      endif()
      if("${_runtime_deps}" STREQUAL "_runtime_deps-NOTFOUND")
        set(_runtime_deps)
      endif()

      foreach(_dep ${_build_deps} ${_runtime_deps})
        if(NOT TARGET "${_dep}")
          continue()
        endif()

        # Look up which artifact(s) this dep belongs to.
        get_target_property(_dep_artifacts "${_dep}" THEROCK_ARTIFACT_NAMES)
        if(NOT _dep_artifacts OR "${_dep_artifacts}" STREQUAL "_dep_artifacts-NOTFOUND")
          # Dep has no artifact mapping — it's an infrastructure subproject
          # (e.g. therock-googletest). Skip.
          continue()
        endif()

        # Check if any of the dep's artifacts are satisfied by the topology.
        set(_satisfied FALSE)
        foreach(_dep_artifact ${_dep_artifacts})
          if("${_dep_artifact}" STREQUAL "${_artifact}")
            # Same artifact — handled by CMake ordering, not topology.
            set(_satisfied TRUE)
            break()
          endif()
          if("${_dep_artifact}" IN_LIST _topology_deps)
            set(_satisfied TRUE)
            break()
          endif()
          # If the dep artifact's feature is OFF but the dep target still
          # exists, the subproject is declared unconditionally (outside any
          # if(THEROCK_ENABLE_*) guard). It will always be available
          # regardless of which features are enabled, so topology coverage
          # is not required.
          set(_dep_feature "${THEROCK_ARTIFACT_FEATURE_${_dep_artifact}}")
          if(_dep_feature AND NOT THEROCK_ENABLE_${_dep_feature})
            set(_satisfied TRUE)
            break()
          endif()
        endforeach()

        if(NOT _satisfied)
          # Pick the first dep artifact for the error message.
          list(GET _dep_artifacts 0 _dep_artifact_name)
          list(APPEND _errors
            "Subproject '${_subproject}' (artifact '${_artifact}') depends on "
            "'${_dep}' (artifact '${_dep_artifact_name}'), but "
            "BUILD_TOPOLOGY.toml has no dependency path from '${_artifact}' to "
            "'${_dep_artifact_name}'. Add '${_dep_artifact_name}' to "
            "artifact_deps for '${_artifact}' in BUILD_TOPOLOGY.toml.\n"
          )
        endif()
      endforeach()
    endforeach()
  endforeach()

  if(_errors)
    list(JOIN _errors "" _error_msg)
    message(FATAL_ERROR
      "Topology validation failed: CMake subproject dependencies are not "
      "reflected in BUILD_TOPOLOGY.toml.\n\n${_error_msg}"
      "This means enabling a feature in isolation (e.g. "
      "-DTHEROCK_ENABLE_<X>=ON) may fail because transitive dependencies "
      "won't be automatically enabled.\n"
    )
  endif()
endfunction()
