name: Build Windows PyTorch Wheels

on:
  workflow_call:
    inputs:
      AMDGPU_FAMILIES:
        required: true
        type: string
      python_version:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      AMDGPU_FAMILIES:
        required: true
        type: string
      python_version:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build_pytorch_wheels:
    name: Build Windows PyTorch Wheels | ${{ inputs.AMDGPU_FAMILIES }} | Python ${{ inputs.python_version }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-windows-scale-rocm' || 'windows-2022' }}
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
      S3_BUCKET: ${{ inputs.s3_bucket }}
      S3_ENDPOINT: "s3.us-east-2.amazonaws.com"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure Git Identity
        run: |
          git config --global user.name "therockbot"
          git config --global user.email "therockbot@amd.com"

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ inputs.python_version }}

      # TODO(amd-justchen): share with build_windows_packages.yml. Include in VM image? Dockerfile?
      - name: Install requirements
        run: |
          choco install --no-progress -y ninja
          choco install --no-progress -y awscli
          echo "$PATH;C:\Program Files\Amazon\AWSCLIV2" >> $GITHUB_PATH

      # TODO(#827): replace with latest nightly, or source build, or pip install
      #                  just hardcoding for now to get things off the ground...
      - name: Download ROCm
        run: |
          aws s3 cp s3://therock-dev-tarball/therock-dist-windows-gfx110X-dgpu-6.5.0.dev0+8fa909d3ab28e3c728d79334f6339a6ab933f787.tar.gz . --no-sign-request --no-progress
          mkdir -p rocm-tarball
          tar -xf *.tar.gz -C rocm-tarball
          ls -lh rocm-tarball

      - name: Checkout PyTorch Source Repos
        run: |
          python ./external-builds/pytorch/pytorch_torch_repo.py checkout
      # TODO(#827): include these
          # python ./external-builds/pytorch/pytorch_audio_repo.py checkout
          # python ./external-builds/pytorch/pytorch_vision_repo.py checkout

      - name: Build PyTorch
        env:
          ROCM_HOME: rocm-tarball
        run: |
          echo "Building PyTorch wheels for ${{ inputs.AMDGPU_FAMILIES }}"
          bash ./external-builds/pytorch/build_pytorch_windows.sh ${{ inputs.AMDGPU_FAMILIES }}

      # TODO: have script do this itself, during the build
      - name: Copy wheels to output dir
        run: |
          cp ./external-builds/pytorch/pytorch/dist/*.whl ${{ env.PACKAGE_DIST_DIR }}
          ls -lh ${{ env.PACKAGE_DIST_DIR }}

      # TODO(#827): add upload once working

      # - name: Upload wheels to S3
      #   if: ${{ github.repository_owner == 'ROCm' }}
      #   run: |
      #     aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://${{ env.S3_BUCKET }}/${{ inputs.AMDGPU_FAMILIES }}/ \
      #       --recursive --exclude "*" --include "*.whl"

      # - name: (Re-)Generate Python package release index
      #   if: ${{ github.repository_owner == 'ROCm' }}
      #   run: |
      #     pip install boto3
      #     python ./build_tools/packaging/python/generate_release_index.py \
      #       --bucket=${{ env.S3_BUCKET }} \
      #       --endpoint=${{ env.S3_ENDPOINT }} \
      #       --subdir=${{ inputs.AMDGPU_FAMILIES }} \
      #       --output=${{ github.workspace }}/index.html
      #     aws s3 cp ${{ github.workspace }}/index.html s3://${{ env.S3_BUCKET }}/${{ inputs.AMDGPU_FAMILIES }}/
