name: Build Python Packages

on:
  workflow_dispatch:
    inputs:
      version_spec:
        required: false
        type: string
      package_suffix:
        required: false
        type: string

  workflow_call:
    inputs:
      version_spec:
        required: false
        type: string
      package_suffix:
        required: false
        type: string

jobs:
  build_python_packages:
    name: Build Python Packages
    runs-on: azure-cpubuilder-linux-scale
    container:
      image: ghcr.io/nod-ai/therock_build_manylinux_x86_64:main
    strategy:
      fail-fast: true
    env:
      CACHE_DIR: ${{ github.workspace }}/.container-cache
      CCACHE_DIR: "${{ github.workspace }}/.container-cache/ccache"
      CCACHE_MAXSIZE: "700M"
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Report Runner Health
        run: |
          echo "CCACHE_DIR=${CCACHE_DIR}"
          df -h
          ccache -z
          mkdir -p $CCACHE_DIR
          cmake --version
          echo "Installed Python versions:"
          ls -d /opt/python
          echo "python: $(which python), python3: $(which python3)"
          echo "Git version: $(git --version)"

      # TODO: We shouldn't be using a cache on actual release branches, but it
      # really helps for iteration time.
      - name: Enable cache
        uses: actions/cache/restore@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: ${{ env.CACHE_DIR }}
          key: build-python-manylinux-v2-${{ github.sha }}
          restore-keys: |
            build-python-manylinux-v2-

      - name: Fetch sources
        run: |
          ./build_tools/fetch_sources.py --depth 1

      # The full checkout is very large: ~16GB, 9 of which is GIT stuff.
      # So we delete the latter. This must be done after getting any git
      # stamps or such things.
      - name: Trim Disk Space
        run: |
          rm -Rf sources/.repo
          df -h

      - name: Build Projects
        run: |
          cd python_projects/runtime
          export THEROCK_PY_VERSION="${{ inputs.version_spec }}"
          export THEROCK_PY_SUFFIX="${{ inputs.package_suffix }}"
          export CMAKE_C_COMPILER_LAUNCHER=ccache
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          echo "Building package ${THEROCK_PY_VERSION}"
          pip wheel -v .
          auditwheel repair TheRock_runtime*.whl

      - name: Report
        if: ${{ !cancelled() }}
        run: |
          ccache -s
          cd python_projects/runtime
          ls -lh . wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: TheRock-runtime-linux-x86_64-python
          path: |
            python_projects/runtime/wheelhouse/*.whl
          if-no-files-found: warn

      - name: Save cache
        uses: actions/cache/save@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        if: always()
        with:
          path: ${{ env.CACHE_DIR }}
          key: build-python-manylinux-v2-${{ github.sha }}
