name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    name: Test after setup
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Run test command
        run: echo "Hello world"

  # build_linux_packages:
  #   permissions:
  #     id-token: write
  #   name: Build Linux Packages
  #   uses: ./.github/workflows/build_linux_packages.yml
  #   with:
  #     amdgpu_families: "${{ inputs.amdgpu_families != '' && inputs.amdgpu_families || 'gfx94X-dcgpu' }}"

  # build_windows_packages:
  #   name: Build Windows Packages
  #   uses: ./.github/workflows/build_windows_packages.yml

  # test_linux_packages:
  #   needs: build_linux_packages
  #   name: Test Linux Packages
  #   uses: ./.github/workflows/test_linux_packages.yml
  #   with:
  #     amdgpu_families: "${{ inputs.amdgpu_families != '' && inputs.amdgpu_families || 'gfx94X-dcgpu' }}"

  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml
